- .github/workflows/build.yml
- include/ImageData.h
- include/config.h
- platformio.ini
- Run a few [clang-tidy](https://docs.platformio.org/en/latest/advanced/static-code-analysis/tools/clang-tidy.html) checks in CI.
- Address a couple of the warnings it was producing.
- Run CI on PRs
> Static analysis

- include/button.h
- platformio.ini
- src/bl.cpp
- src/button.cpp
- Move the button handling into a separate file
- Wait on a serial connection (when built with `-D WAIT_FOR_SERIAL`) before logging the outcome
Testing this on my device, all three inputs are working (single-click / double-click / long-press).
> Organize button handling

- .gitignore
- include/config.h
- src/api-client/submit_log.cpp
- src/bl.cpp
The Idea behind this PR is separation of concern. Having a different endpoint than the mother app, lets us create dedicated server to serve devices 1000s of devices when they come online and request display data. This is more to future proof scalability when needed.
> Using different API endpoint

- include/config.h
- src/filesystem.cpp
- Fixed redefinition of WIFI_CONNECTION_ATTEMPTS
- Fixed "control reaches end of non-void function" in filesystem_file_rename function
- Deleted unused "WIFI_PORTAL_TIMEOUT" define
> FIxed some build warnings

- platformio.ini
- update espressif32 to 6.9.0
- pin ESPAsyncWebServer to 3.3.0
I haven't tested this on a device yet, but will follow up when I get to it.
> Version updates

- platformio.ini
A new version of ArduinoJson (7.3.0) [broke CI](https://github.com/usetrmnl/firmware/actions/runs/12550275963/job/34992874761). This PR doesn't fix the new error, but pins an older version of the library to avoid it for now.
If only this ecosystem had lockfiles and deterministic package installs! 🤨
> Pin ArduinoJson 7.2.1 to fix build

- src/api-client/submit_log.cpp
This adds the ID header to the `/api/log` call.
Reasoning:
- It improves consistency, as both `/api/setup` and `/api/display` currently receive the device ID.
- It allows you to identify a device which has a bad or expired API key from `/api/log` calls.
- It allows looking up a device by ID on all API calls.
Resolves #80
Tested on device.
> Add ID header to /api/log call

- lib/wificaptive/src/WifiCaptive.cpp
- lib/wificaptive/src/WifiCaptive.h
- platformio.ini
Issue #71
- Remove `_lastUsed`, will shift all network credentials in the array so that last used wifi is `_savedWifis[0]`
- On failed connection to last used WiFi network, loop over all saved credentials in the array
- No longer saves duplicate networks in the array
> Multiple WiFi Network Support

- src/bl.cpp
The current calculations of using a 32 bit int has an overflow when the server gives it a refresh_rate above 4294 seconds (about 70 minutes). 
Switching this to a 64bit integer will allow users to have their devices refresh once a day if they would like.
> Enable Longer Sleep Times

- lib/trmnl/src/parse_response_api_setup.cpp
- platformio.ini
We had to pin ArduinoJSON in de6a88d8eb6d8be8ddc3dcc971ae68783d5ec205. this fixes the compliation error and allows ArduinoJSON to be upgraded.
The error and fix is explained here https://arduinojson.org/v7/proxy-non-copyable/
> Upgrade ArduinoJSON

- src/bl.cpp
Allows for us to standardize on the HTTP response code rather status "status" field in JSON, while maintaining backwards compat with older firmware.
Tested on device.
> add fw-version header to api/setup request

- lib/trmnl/include/api_types.h
- src/bl.cpp
I hope to gradually overhaul `downloadAndShow()`. But to make it easier to review and test, it will take a bunch of small steps to get there. Here's the first one, slicing off a few separate functions related to the `/api/display` call:
- `loadApiDisplayInputs()` to load information out of preferences etc.
- `addHeaders()` to take this information and tack on the headers.
- `handleApiDisplayResponse()` to handle the (many) side effects afterward.
> Small refactor in downloadAndShow()

- .github/workflows/build.yml
This PR:
- ~~makes a couple small changes in platform.ini to allow `pio test -e native` to work with MacOS' current C/++ compiler.~~
- adds CI jobs to build and test on MacOS and Windows.
> Mac and Windows CI

- include/api-client/display.h
- lib/trmnl/include/api_types.h
- lib/trmnl/include/http_client.h
- lib/trmnl/src/parse_response_api_display.cpp
- src/api-client/display.cpp
- src/api-client/submit_log.cpp
- src/bl.cpp
This PR adds a new helper to wrangle some of the common logic around the connection lifecycle. It works like this:
```cpp
return withHttp(binUrl, [&](HTTPClient *https, HttpError errorCode) -> bool {
if(errorCode == HttpError::HTTPCLIENT_WIFICLIENT_ERROR){
// ...
return false;
}
auto httpCode = https->GET();
// ...
return true;
});
```
For now I used it in three places:
- submitLogToApi() (`/api/log`)
- checkAndPerformFirmwareUpdate()
- downloadAndShow (just `/api/display` for now, not the image download)
I've tested this on-device, and seen all three of those operations working.
I thought I'd stop there for now. If we like this approach, I'll follow up later with the other HTTP operations (`/api/setup/` in getDeviceCredentials(), streaming image downloads, etc.)
> HTTP Helper

- src/bl.cpp
If the image is not changed, it is not a problem so we shouldn't enter retry mode.
Otherwise, that's how it works, which doesn't make sense:
```
16:08:36:062 -> I: src/bl.cpp [1124]: Old image. No needed to show it.
16:08:36:064 -> I: src/bl.cpp [1130]: update_firmware: 0
16:08:36:065 -> I: src/bl.cpp [1133]: firmware_url: https://trmnl-fw.s3.us-east-2.amazonaws.com/FW1.5.2.bin
16:08:36:065 -> I: src/bl.cpp [1136]: refresh_rate: 299
16:08:36:066 -> I: src/bl.cpp [1139]: write new refresh rate: 299
16:08:36:070 -> I: src/bl.cpp [1141]: written new refresh rate: 4
16:08:36:071 -> I: src/bl.cpp [1155]: result - 3
16:08:36:074 -> I: src/bl.cpp [991]: Returned result - 0
16:08:36:075 -> I: src/bl.cpp [373]: request result - 0
16:08:36:077 -> I: src/bl.cpp [403]: retry:3 - time to sleep: 30 …
```
> Fix handling downloadAndShow HTTPS_NO_ERR result

- include/config.h
- lib/esp32-waveshare-epd/src/DEV_Config.cpp
- lib/esp32-waveshare-epd/src/DEV_Config.h
- platformio.ini
- src/bl.cpp
I've added support to the official driver for the [Waveshare ESP32 driver board](https://www.waveshare.com/wiki/E-Paper_ESP32_Driver_Board), which makes it really easy to create a TRMNL with just hooking up an e-ink display to this driver board.
The changes required are minimal, as you can see, and I can add some #ifdefs for them. There should be one based on the environment (some of the changes are ESP32-specific), but there are things like faking the battery voltage for builds that don't use a battery.
Are there any specific defines you guys would like to see, or any opinions you have on this?
> Add support for Waveshare E-Paper ESP32 Driver Board

- platformio.ini
The 1.1.2 contains proper fix for png structure decoding & protection against header corruptions.
> Update PNGdec to 1.1.2 release.

- lib/trmnl/include/mock_log.h
Today the unit tests use a mock ArduinoLog, but the implementation is empty. This PR implements the mock logger, so that stdout messages appear when you run unit tests with `-v`, e.g.:
```
> pio test -e native --filter test_bmp -v
Collected 4 tests (test_bmp, test_parse_api_display, test_parse_api_setup, test_png_flip)
Processing test_bmp in native environment
----------------------------------------------------------------------------------------------------------------------------
Building...
Testing...
[INFO] lib/trmnl/src/bmp.cpp [33]: BMP Header Information:
Width: 800
Height: 480
Bits per Pixel: 1
Compression Method: 0
Image Data Size: 48000
Color Table Entries: 2
Data offset: 62
[INFO] lib/trmnl/src/bmp.cpp [42]: Color table
[INFO] lib/trmnl/src/bmp.cpp [45]: Color 1: B-0, R-0, G-0 …
```
> Display log output during unit tests

- src/bl.cpp
Set HTTPS timeout to 15s instead of old 5s to fight server-side slowness and weak Wifi signals.
> Set HTTPS timeout to 15s instead of old 5s

- lib/wificaptive/src/WifiCaptive.cpp
When the last used WiFi network failed to connect, the loop over saved networks incorrectly skipped the most recently added network (index 0) instead of the last used network (stored in last_used_index)
> Fix autoConnect to Use Last Used WiFi Index Correctly

- lib/wificaptive/src/WifiCaptive.cpp
Hi there,
i frequently got issues with both of my TRMNL, not being able to reconnect to my Wi-Fi. Getting `Can't establish WiFi connection.` error messages frequently.
I read somewhere online that the ESP32-C3 being a single core processor and frequently reconnecting to Wi-Fi is challenging. I added this exponential back-off to the Wi-Fi auto-connection and haven't seen any problems in the last 48 hrs. I usually got them after 5-6 hrs of operation.
> add exponential backoff to WiFi retries

- include/types.h
- lib/wificaptive/src/WebServer.cpp
- lib/wificaptive/src/WebServer.h
- lib/wificaptive/src/WifiCaptive.cpp
- lib/wificaptive/src/WifiCaptive.h
- lib/wificaptive/src/wifi-types.h
Some small steps toward better organization of `lib/wificaptive`:
- pull `setUpWebserver()` into a separate function to decouple it from `WifiCaptive`
- use `WifiCredentials` struct more broadly instead of passing around ssid / password Strings
- add new `tryConnectWithRetries()` helper based on repeated pattern
I intend to do more here, but this is a good stopping point for a PR. I tested it on-device and the captive portal is working fine.
> Small wifi refactor

- .github/workflows/build.yml
Here's a new CI job which will produce (and upload!) a firmware image on every `main` commit. You can go in the job history and download it.
Eventually this could be hooked in to the [release](https://github.com/usetrmnl/trmnl-firmware/releases) process so that it doesn't depend on manually performing builds on anyone's workstation.
> publish-build job

- .github/workflows/build.yml
- include/config.h
- platformio.ini
- scripts/git_version.py
- src/bl.cpp
It's hard to keep track of whether my devices are on release builds or custom builds. This small change adds a suffix to tell them apart:
> version suffix for local/CI builds

- .github/workflows/build.yml
- .github/workflows/publish-firmware.yml
After #174, each commit on `main` produces an "engineering build", with a filename like `trmnl-merged.75bb220.bin` and a reported firmware version of `1.5.9+75bb220`.
This PR wires up builds each time a git tag is pushed, producing a filename like `trmnl-merged.v1.5.9.bin` and a reported firmware version of `1.5.9`. (note that this reported version is still driven by the values in config.h, not by the git tag)
Hopefully this can replace some of the manual work that goes in to releasing firmware!
> tagged release builds produced by CI

- include/config.h
- platformio.ini
- scripts/git_version.py
rename a config to avoid this warning:
```
Warning! Ignore unknown configuration option `include_git_hash` in section [env:trmnl]
```
> Avoid pio warning

- include/config.h
- src/bl.cpp
This will make it less error-prone to work with (never have to `.c_str()` it)
> Fove firmware version string into compile-time constant

- lib/trmnl/include/logging_parcers.h
- lib/trmnl/src/logging_parsers.cpp
- lib/wificaptive/src/WifiCaptive.cpp
- lib/wificaptive/src/WifiCaptive.h
- lib/wificaptive/src/connect.cpp
- lib/wificaptive/src/connect.h
- lib/wificaptive/src/wifi-helpers.cpp
- lib/wificaptive/src/wifi-helpers.h
- lib/wificaptive/src/wifi-types.h
- src/bl.cpp
Capture more detail during WiFi connection attempts. For now it's just logged. Here are a few examples:
```
I: src/bl.cpp [268]: Hardcoded WiFi: connecting to SSID 'test-wpa2'
I: lib/wificaptive/src/connect.cpp [51]: WiFi: begin, starting from status disconnected
I: lib/wificaptive/src/connect.cpp [23]: Wifi: Event STA_CONNECTED SSID: test-wpa2, BSSID: DA:F9:21:84:BC:3F, channel: 6, authmode: 3
I: lib/wificaptive/src/connect.cpp [77]: WiFi: status changed from disconnected to idle_status
I: lib/wificaptive/src/connect.cpp [16]: Wifi: Event STA_GOT_IP, IP: 192.168.0.233, Gateway: 192.168.0.1
I: lib/wificaptive/src/connect.cpp [77]: WiFi: status changed from idle_status to connected
I: src/bl.cpp [270]: Hardcoded WiFi: connect result 'connected'
```
```
I: src/bl.cpp [268]: Hardcoded WiFi: …
```
> Log more WiFi connection error detail

- src/bl.cpp
- src/display.cpp
Here are my propositions for the week-end\
- fix for PNG payload > 48062 reendered as static
- fix for G5 (small)logo processed as PNG (in loading screen)
- removal of most malloc/free  buffer in bl.cpp
- only clear screen when G5 bitmap is not fullscreen in display_show_msg x2)
> fix for PNG payload > 48062 and malloc/free removed

- platformio.ini
- src/display.cpp
great for Alias, Redirect plugin use case. does use a bit more power, writeup coming soon.
1. point to a color image
2. just works
**requirements**
PNG, 800x480 (for now), < 90000 bytes.
> Color PNG support

- src/display.cpp
Log terminology now differs for both homonym functions display_show_msg
I would rename one of them as it can be confusing
I discussed this static issue with @Fr3dr1ckson but he did not confirm the fix works
To reproduce the issue in FW 1.6.7 or 1.6.6 : hold back button for more than 10s to trigger a Wifi reset.
The blank screen before qrcode screen is not blank but has garbage/static
> Fix for static when resetting Wifi
